# Generated by Django 4.0.5 on 2022-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupant_Name', models.CharField(help_text='your name, surname first', max_length=300)),
                ('Occupant_Email', models.EmailField(max_length=254)),
                ('Occupant_Occupation', models.CharField(max_length=200)),
                ('Amount_Pad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Room_Number', models.IntegerField()),
                ('No_of_Night', models.IntegerField()),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
            ],
        ),
    ]
