# Generated by Django 4.0.5 on 2022-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Amount_Pad',
        ),
        migrations.AddField(
            model_name='record',
            name='Amount_Paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
