# Generated by Django 4.0.5 on 2022-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_record_amount_pad_record_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Amount_Paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
